services:
  - type: web
    name: pons-backend
    runtime: node
    branch: main
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: pons-frontend
    runtime: static
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    envVars:
      - key: VITE_API_BASE
        sync: false
